#!/usr/bin/env python3
"""Emit a pip constraints file pinning every runtime dependency to its floor.

`[project.dependencies]` states a minimum for each runtime dependency, and
until 2026-09-20 nothing had ever installed those minimums -- CI resolves
whatever is newest, so `numpy>=1.24` was a sentence rather than a claim
anyone had checked. This turns each `>=X` into `==X`, and the floors job
installs exactly what the declaration promises.

DERIVED, NOT DUPLICATED. A second hand-written list of floors would drift
from the first one silently, and the drift would look like a passing job.

REFUSES RATHER THAN SKIPS. A dependency with no `>=` cannot be floor-tested,
and emitting nothing for it would leave the job installing the newest version
while still reporting that it tested the floor. That is the one failure worth
guarding against here, so it is an error.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

try:  # 3.11+
    import tomllib
except ModuleNotFoundError:  # 3.10, which this project still supports
    import tomli as tomllib

#: `name>=1.2.3`, with optional extras and any trailing qualifiers. The floor
#: is the first `>=` in the specifier; `!=` exclusions after it do not move it.
_FLOOR = re.compile(r"^\s*(?P<name>[A-Za-z0-9._-]+)\s*(?:\[[^\]]*\])?\s*(?P<rest>.*)$")


def floor_of(spec: str) -> tuple[str, str | None, list[str]]:
    """Return ``(name, floor, exclusions)`` for one dependency specifier."""
    match = _FLOOR.match(spec)
    if not match:
        return spec.strip(), None, []
    name = match.group("name")
    rest = match.group("rest")
    found = re.search(r">=\s*([0-9][^,;\s]*)", rest)
    exclusions = re.findall(r"!=\s*([0-9][^,;\s]*)", rest)
    return name, (found.group(1) if found else None), exclusions


def main() -> int:
    pyproject = Path("pyproject.toml")
    data = tomllib.loads(pyproject.read_text(encoding="utf-8"))
    dependencies = data["project"]["dependencies"]

    lines: list[str] = []
    missing: list[str] = []
    contradictory: list[str] = []
    for spec in dependencies:
        name, floor, exclusions = floor_of(spec)
        if floor is None:
            missing.append(name)
            continue
        # An exclusion can rule out the very version the floor names. The pin
        # below would then contradict the specifier it came from, and
        # `pip install -c` dies with ResolutionImpossible on the runner before
        # a single test is collected. Refuse here instead, where it is cheap.
        if floor in exclusions:
            contradictory.append(f"{name}: floor {floor} is excluded by the same specifier")
            continue
        lines.append(f"{name}=={floor}")

    if contradictory:
        print(
            f"{pyproject}: " + "; ".join(contradictory) + ". Raise the floor above "
            "the excluded version, or drop the exclusion.",
            file=sys.stderr,
        )
        return 1

    if missing:
        print(
            f"{pyproject}: no `>=` floor for {', '.join(sorted(missing))}. "
            "A dependency without a floor cannot be floor-tested, and emitting "
            "nothing for it would let the floors job install the newest version "
            "and still call it a floor. Give it a floor or drop it from "
            "[project.dependencies].",
            file=sys.stderr,
        )
        return 1

    print("# Generated by scripts/floor_constraints.py -- do not edit.")
    print("# Every runtime dependency at the minimum pyproject.toml declares.")
    for line in lines:
        print(line)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
